import type { Locale } from '../../shared/contracts';

export interface Section {
  readonly heading: string;
  readonly paragraphs: readonly string[];
}

export interface EditorialCopy {
  readonly navigation: readonly [string, string, string, string, string];
  readonly skip: string;
  readonly intro: string;
  readonly archiveIntro: string;
  readonly spoiler: string;
  readonly answer: string;
  readonly references: string;
  readonly related: string;
  readonly contact: string;
  readonly notFound: string;
  readonly howTo: readonly Section[];
  readonly about: readonly Section[];
  readonly privacy: readonly Section[];
  readonly articles: Readonly<Record<string, readonly Section[]>>;
}

export const editorialCopy: Readonly<Record<Locale, EditorialCopy>> = {
  en: {
    navigation: ['Play today', 'How to play', 'Past puzzles', 'About & contact', 'Privacy'],
    skip: 'Skip to content',
    intro: 'Ten cards. Four groups. One hidden rule.',
    archiveIntro: 'Selected past Tensift puzzles, with the reasoning behind each answer. Start with a topic you recognize, try your own grouping, then compare your reasoning with the explanation. This is a curated collection, not a complete daily archive.',
    spoiler: 'This page contains the answer to a past puzzle. Today’s puzzle is separate.',
    answer: 'The grouping', references: 'References and further reading', related: 'Keep exploring',
    contact: 'Contact the maintainer or report a correction on GitHub', notFound: 'Page not found',
    howTo: [
      { heading: 'One rule for all ten cards', paragraphs: ['Tensift is a daily classification puzzle. You see ten items connected by a broad topic, but the property that separates them is hidden. Arrange every card into four rows with one, two, three and four spaces. The row sizes are clues to the distribution, not names for the categories.', 'A convincing solution uses the same kind of fact across all four rows. If one row describes where something is found, another describes its color and a third describes its size, step back: you may be mixing rules. First propose a property, then check whether it explains all ten cards.'] },
      { heading: 'Move, check and revise', paragraphs: ['Select a card and then select an empty space, or drag the card onto the board. With a keyboard, focus a card, select it, then focus and activate a destination. A placed, unlocked card can be returned to the tray. Shuffle changes the tray order; it does not change the answer.', 'Fill all ten spaces before checking. Checks are unlimited, and the feedback reports the total number of correctly grouped cards. It does not identify which individual cards are correct. Change a small part of your arrangement between checks so that the new total tells you something useful.'] },
      { heading: 'A worked practice example', paragraphs: ['Imagine ten cards labeled 0 through 9. A possible rule is the remainder after dividing by 4. The four groups are {3, 7}, {2, 6}, {1, 5, 9}, and {0, 4, 8}. Their sizes are 2, 2, 3, 3, so this rule cannot fit a Tensift board—even though it classifies every card consistently.', 'Now imagine cards A, B, C, D, E, F, G, H, I and J marked respectively with 1, 2, 2, 3, 3, 3, 4, 4, 4 and 4 dots. Grouping by dot count produces A / B C / D E F / G H I J. That fits 1 / 2 / 3 / 4 and applies one property everywhere. The lesson is to test both the meaning of your rule and the group counts.'] },
      { heading: 'Hints, answers and daily play', paragraphs: ['One hint can place and lock a card in its correct row. Use that fixed card to reconsider the surrounding groups. Reveal answer opens the intended grouping and explanation; it is available whenever you want to stop guessing. There is no penalty for learning from an explanation.', 'The daily schedule uses UTC. Language and theme preferences, along with saved puzzle progress, are stored in this browser. Clearing site data removes that local progress; it is not an account-based backup. Sharing a result sends a text summary without the answer, through your device’s share sheet or clipboard.'] },
    ],
    about: [
      { heading: 'A small puzzle about changing perspective', paragraphs: ['Tensift asks you to find a useful way to sort familiar things. The ten-card format keeps the board compact, while the unequal row sizes make the category counts part of the deduction. The aim is a short moment of discovery, followed by an explanation you can understand.', 'The game is available in English, Simplified Chinese and Spanish. The public source repository is maintained under the GitHub account frobel0520. You can play without creating an account.'] },
      { heading: 'How to read our explanations', paragraphs: ['Each selected archive page includes the original items, intended groups, a reasoning path and a discussion of misleading alternatives. References provide background; they do not endorse Tensift or independently certify that a puzzle has only one answer.', 'Some classifications use an everyday convention rather than a scientific taxonomy. We state that distinction where it matters. The archive is an editorial selection and does not imply that every scheduled puzzle has passed independent blind playtesting.'] },
      { heading: 'Corrections and contact', paragraphs: ['If a card has two plausible homes, tell us the puzzle date, language, proposed grouping and why it fits. A specific counterexample is more useful than a score alone. For a technical bug, include your browser and the steps that led to the problem.', 'Use the repository’s Issues page to reach the maintainer. GitHub issues are public: do not include passwords, private contact details or other sensitive information.'] },
    ],
    privacy: [
      { heading: 'What stays in your browser', paragraphs: ['Updated 19 September 2026. Tensift stores language, theme and puzzle progress in localStorage on your device. Progress includes card placements, attempts and hint usage. You can remove it with your browser’s site-data controls. This also removes saved preferences and progress.', 'The game does not offer user accounts or cross-device synchronization. Its application code does not currently include an analytics service.'] },
      { heading: 'Requests needed to operate the game', paragraphs: ['When you load a puzzle or request a check, hint or answer, your browser sends the relevant game data to Tensift’s server endpoints hosted on Cloudflare. Hint and reveal requests include a randomly generated client-session identifier. The server stores action receipts with expiry timestamps to handle repeated requests.', 'Cloudflare receives ordinary connection information, such as your IP address and request headers, when serving the site. Hosting and security processing are governed by Cloudflare’s privacy policy. Tensift also uses a maintenance-status service operated through Cloudflare; any preview-access cookie is for maintenance access, not an advertising profile.'] },
      { heading: 'Advertising and external links', paragraphs: ['Ad serving is currently disabled on Tensift pages. AdSense ownership metadata and the ads.txt verification endpoint remain, but they do not by themselves load an advertising script. If advertising is enabled in the future, this notice and any required consent controls must be updated before ad requests begin.', 'Google advertising, when enabled, can use cookies or other identifiers and process IP addresses and usage information for ad delivery, measurement and, where applicable, personalization. Read Google’s partner-site privacy information below for details.', 'Following a reference or contact link takes you to another provider. Sharing is initiated by you through your device’s share sheet or clipboard. Please review what you share. For questions or corrections, contact the maintainer through the public GitHub repository without posting sensitive personal data.'] },
    ],
    articles: {
      countries: [
        { heading: 'Find the scale of the question', paragraphs: ['Start with the four European countries. They form a plausible four-card row without needing a detail such as currency, language or population. Brazil and Argentina suggest a second geographic group. Together, those observations make a continent-based interpretation worth testing.', 'Australia then occupies the one-card row, leaving Canada, Mexico and the United States together. Count every group before committing: the useful evidence is that a single geographic convention accounts for all ten cards in exactly the required sizes.'] },
        { heading: 'Why language is a tempting wrong turn', paragraphs: ['Shared languages can connect some of these countries, but that hypothesis does not produce the same complete partition. A partial association is not enough: if your rule works for three cards and leaves several exceptions, compare it with a rule that handles the entire board.', 'Treat the one-card row as a cross-check, not your first certainty. Almost any country can be made unique by choosing a sufficiently specific fact. It becomes meaningful only when the same property organizes the other nine.'] },
        { heading: 'A note on geographic conventions', paragraphs: ['This puzzle uses Oceania and separates North America from South America. Other educational traditions count continents differently. Mexico belongs in the North America row here; “Latin America” is a different grouping and would change the problem.', 'The linked UN M49 table is a reference for geographic regions and country placement, not a claim that all its statistical subdivisions equal this puzzle’s four categories. Read the rule with the stated convention in mind rather than assuming every regional label is interchangeable.'] },
      ],
      animals: [
        { heading: 'Test identity, not where an animal lives', paragraphs: ['The dolphin and penguin are useful stress tests for a proposed rule. Grouping everything that swims together feels natural, but it mixes animals with different biological characteristics. Try a classification that remains useful when an animal changes its surroundings.', 'The intended everyday vertebrate groups give the frog a one-card row, crocodile and turtle a two-card row, and eagle, penguin and parrot a three-card row. The remaining four belong together. Check the entire partition rather than treating “the leftovers” as a separate rule.'] },
        { heading: 'What the surprising cards teach', paragraphs: ['A penguin belongs with the other birds despite not flying. A dolphin belongs with the other mammals despite living in water. These cards expose the difference between a visible behavior and the category the puzzle is using.', 'A useful solving habit is to name your rule aloud: “how it moves” and “what kind of animal it is” are different questions. When one card keeps resisting a grouping, reconsider the question before assuming the card is an exception.'] },
        { heading: 'The limits of this simplified classification', paragraphs: ['The answer uses familiar school-level group names. It is not a complete evolutionary tree: modern phylogenetic treatments place birds within the reptile lineage. Here, “reptiles” means the conventional non-avian group used in the exercise.', 'That qualification matters because a puzzle needs a clear convention as well as familiar examples. If you find an alternative that applies consistently to all ten animals and preserves 1 / 2 / 3 / 4, report the full grouping so it can be examined.'] },
      ],
      instruments: [
        { heading: 'Listen to how the sound begins', paragraphs: ['The most useful starting contrast is between the drum and the instruments with vibrating strings. The drum stands alone in this selection, while violin, guitar, cello and harp fill the four-card row. Those counts suggest a familiar instrument-family convention.', 'The remaining five all involve air, but one five-card group will not fit. Trumpet and trombone form the pair; flute, clarinet and oboe form the trio. A good rule explains why that split is meaningful, rather than simply using row sizes to force unrelated cards together.'] },
        { heading: 'Why the material can mislead', paragraphs: ['A metal flute does not move into the brass family just because of its material. In this convention, the way sound is produced matters more than the substance of the instrument’s body. That is why “made of metal” is a poor replacement for the intended rule.', 'The string row also contains different playing techniques. Guitar and harp are commonly plucked; violin and cello are commonly bowed. Separating by those techniques would answer a narrower question and would break the four-card group.'] },
        { heading: 'Use the convention at the right level', paragraphs: ['These are familiar instrument families, not a comprehensive catalog of every instrument or every acoustical classification system. The selected cards avoid instruments such as the piano, which can invite discussion about strings, striking actions and keyboard groupings.', 'When evaluating an alternative answer, ask whether the same level of description applies to every row. A family in one row and a playing technique in another would mix levels. Carry this check into the next puzzle: keep both the property and its level of detail consistent.'] },
      ],
    },
  },
  'zh-Hant': {
    navigation: ['今日謎題', '玩法指南', '過往謎題', '關於與聯絡', '隱私說明'],
    skip: '跳到正文', intro: '十張卡片。四個分組。一個隱藏規則。',
    archiveIntro: '這裡精選已經結束的 Tensift 謎題，解釋答案背後的思路。先選一個熟悉的主題，嘗試自己的分類，再對照解析。這是精選題解集，並非完整的每日存檔。',
    spoiler: '本頁包含過往謎題答案，與今日謎題分開。', answer: '完整分組', references: '參考資料與延伸閱讀', related: '繼續探索',
    contact: '在 GitHub 聯絡維護者或提交更正', notFound: '找不到這個頁面',
    howTo: [
      { heading: '用同一條規則解釋十張卡', paragraphs: ['Tensift 是每日分類謎題。十張卡片共享一個可見主題，但真正的分類角度需要你發現。把它們放進容量為 1、2、3、4 的四列。數字只告訴你每組的數量，不會直接告訴你組名。', '一個合理的解法應該對所有分組使用同一種事實。如果一列按地點，另一列按顏色，第三列又按大小，就可能混用了規則。先提出分類角度，再檢查它是否能解釋全部十張卡。'] },
      { heading: '移動、檢查與修正', paragraphs: ['點選卡片，再點選空格即可放置，也可以拖曳。使用鍵盤時，先聚焦並選取卡片，再聚焦並啟用目標格。已經放置但沒有鎖定的卡片可以退回待選區。「打亂」只改變待選卡片順序，不改變答案。', '填滿十個格子後才能檢查，次數不限。回饋只會告訴你正確歸類的總數，不會指出具體哪張正確。每次只調整一小部分，再比較正確數量，通常比一次全部重排更容易獲得線索。'] },
      { heading: '用一個練習理解數量線索', paragraphs: ['假設十張卡片是數字 0 到 9，按除以 4 的餘數分類，可以得到 {3, 7}、{2, 6}、{1, 5, 9}、{0, 4, 8}。規則雖然一致，數量卻是 2、2、3、3，不能放進 Tensift 的棋盤。規則合理與數量吻合，兩者都必須滿足。', '再假設 A 到 J 十張卡片分別標有 1、2、2、3、3、3、4、4、4、4 個圓點。按圓點數量分類，就得到 A / B C / D E F / G H I J，正好符合 1 / 2 / 3 / 4。實際謎題會隱藏這個角度，但驗證方法相同。'] },
      { heading: '提示、揭曉與每日進度', paragraphs: ['每題有一次提示，會把一張卡放到正確的列並鎖定。你可以用它重新檢查其他分組。想停止猜測時，隨時選擇「顯示答案」，閱讀預設分組與解釋。看懂解析也是遊戲的一部分。', '每日排程使用 UTC。語言、主題及謎題進度儲存在目前的瀏覽器，清除網站資料會刪除這些記錄，並不會同步到其他裝置。分享功能透過裝置分享選單或剪貼簿提供不含答案的文字結果。'] },
    ],
    about: [
      { heading: '練習換個角度看熟悉的事物', paragraphs: ['Tensift 把十個熟悉的項目放在同一個棋盤上，邀請你尋找一致的分類方法。四列不相等的容量，讓數量本身也成為推理線索。我們希望每題帶來一次短暫的發現，也提供能讀懂的解釋。', '遊戲支援英語、繁體中文和西班牙語，無需註冊。公開原始碼由 GitHub 帳號 frobel0520 維護。'] },
      { heading: '如何閱讀題解', paragraphs: ['精選題解包含原始卡片、預設分組、推理過程及容易混淆的其他角度。參考資料用於補充背景，不代表來源機構為 Tensift 背書，也不代表它們驗證過答案的唯一性。', '有些分類採用日常慣例，而不是完整的科學分類系統；我們會在相關解析中說明。精選題解不代表所有排程題目均已透過獨立盲測。'] },
      { heading: '更正與聯絡', paragraphs: ['如果某張卡有兩個合理歸屬，請提供題目日期、語言、完整的替代分組與理由。一個具體反例比單純的分數更能幫助改進。報告技術問題時，請附上瀏覽器名稱和重現步驟。', '你可以透過專案的 GitHub Issues 聯絡維護者。Issue 是公開的，請不要提供密碼、私人聯絡方式或其他敏感資料。'] },
    ],
    privacy: [
      { heading: '儲存在瀏覽器中的資料', paragraphs: ['更新日期：2026 年 9 月 19 日。Tensift 使用裝置上的 localStorage 儲存語言、主題及謎題進度，包括卡片位置、嘗試次數和提示使用情況。你可以透過瀏覽器的網站資料設定刪除它們，同時也會失去已儲存的偏好與進度。', '遊戲目前沒有帳號及跨裝置同步功能，應用程式程式碼目前沒有接入統計分析服務。'] },
      { heading: '遊戲執行所需的請求', paragraphs: ['載入謎題、檢查排列、請求提示或揭曉答案時，瀏覽器會把相關遊戲資料傳送到部署在 Cloudflare 的 Tensift 伺服器介面。提示及揭曉請求帶有隨機產生的用戶端工作階段識別碼；伺服器儲存帶過期時間的操作記錄，以處理重複請求。', 'Cloudflare 提供網站服務時會接收 IP 位址及請求標頭等一般的連線資訊，其託管與安全處理適用 Cloudflare 隱私政策。Tensift 也使用經 Cloudflare 執行的維護狀態服務；維護預覽的存取 Cookie 用於存取控制，而非廣告畫像。'] },
      { heading: '廣告與外部連結', paragraphs: ['Tensift 頁面目前停用廣告投放。AdSense 所有權後設資料與 ads.txt 驗證介面仍然保留，但它們本身不會載入廣告腳本。未來啟用廣告之前，必須更新此說明並設定所需的同意控制。', '啟用後，Google 廣告可能使用 Cookie 或其他識別碼，並處理 IP 位址與使用資訊，用於廣告投放、衡量及適用情況下的個人化。詳情請參閱下方 Google 合作網站隱私說明。', '點選參考資料或聯絡連結會前往其他服務。分享由你透過裝置選單或剪貼簿主動發起，請檢查分享內容。如有問題，可透過公開 GitHub 專案聯絡維護者，但請勿公開敏感個人資料。'] },
    ],
    articles: {
      countries: [
        { heading: '先找對地理尺度', paragraphs: ['法國、德國、義大利和西班牙可以組成四張卡的一組，無需先猜貨幣、人口或語言。巴西與阿根廷又提示了另一組地理關聯。把兩條線索放在一起，按洲劃分就值得嘗試。', '接著，澳洲進入單張卡的列，加拿大、墨西哥和美國組成三張卡的列。真正有用的證據不是某兩國有關聯，而是同一種地理慣例能讓全部十張卡恰好符合四列容量。'] },
        { heading: '為什麼語言容易讓人走偏', paragraphs: ['共同語言能夠連結部分國家，卻不一定產生相同的完整劃分。如果一個想法只能解釋三張卡，其他卡片卻需要不斷增加例外，就應該拿它與能夠解釋整張棋盤的規則比較。', '單張卡的列更適合用來驗證，而不是最先認定。只要挑選足夠特殊的事實，幾乎每個國家都能顯得獨一無二。只有當同一屬性也能整理其他九張卡時，這種獨特性才有意義。'] },
        { heading: '這裡採用的地理慣例', paragraphs: ['本題使用「大洋洲」，並將北美洲與南美洲分開。不同教育傳統對洲的數量可能有不同處理。這裡墨西哥屬於北美洲；「拉丁美洲」是另一種劃分，不能直接替換。', '聯合國 M49 表可用於查閱地理區域和國家位置，但其統計分區層級並不等同於本題的四個組名。閱讀資料時，要注意分類所採用的範圍與層級。'] },
      ],
      animals: [
        { heading: '先問是什麼動物，而不是住在哪裡', paragraphs: ['海豚和企鵝特別適合檢驗你的規則。把會游泳的動物放在一起很直覺，卻混合了不同生物類別。試著尋找一種不會隨著活動地點改變而改變的分類方式。', '本題採用的常見脊椎動物分組讓青蛙單獨一列，鱷魚與烏龜佔兩格，鷹、企鵝與鸚鵡佔三格，其餘四種歸為一組。必須驗證最後一組的共同點，而不能只把它當作「剩下的卡片」。'] },
        { heading: '最容易誤放的兩張卡', paragraphs: ['企鵝雖然不會飛，仍與其他鳥類放在一起；海豚雖然生活在水中，仍與其他哺乳動物放在一起。它們提示我們：可見行為與本題採用的類別，是兩種不同線索。', '解題時不妨把規則說成完整問題：「如何移動？」和「屬於哪類動物？」並不相同。遇到一張卡總是放不進去時，先檢查自己問的問題，別急著把它當成例外。'] },
        { heading: '簡化分類的邊界', paragraphs: ['這裡使用熟悉的學校教育分組，不是完整的演化樹。現代系統發育分類會把鳥類放在爬蟲類動物演化支系之內；本題的「爬蟲類動物」採用日常練習中不含鳥類的傳統用法。', '熟悉的名詞仍然需要明確慣例。如果你找到另一種適用於十張卡、同時符合 1 / 2 / 3 / 4 的分類，請提交完整分組，讓我們能夠實際檢查歧義。'] },
      ],
      instruments: [
        { heading: '從聲音如何產生開始', paragraphs: ['鼓與帶弦樂器的對比是很好的起點。鼓在這組卡片中單獨成組，小提琴、吉他、大提琴和豎琴恰好佔滿四格。這些數量提示了熟悉的樂器家族劃分。', '剩下五種都與氣流有關，但棋盤沒有五格的列。小號和長號組成兩張卡的一組，長笛、單簧管和雙簧管組成三張卡的一組。規則應該解釋這種拆分，而不是只為填滿格子硬湊。'] },
        { heading: '材質為什麼會誤導', paragraphs: ['金屬製的長笛不會因為材質就被放進銅管組。在本題採用的慣例中，發聲方式比樂器外殼的材料更重要，因此「是否由金屬製成」不是可靠的替代規則。', '四張弦樂器卡片也包含不同演奏方式：吉他、豎琴常用撥弦，小提琴、大提琴常用弓拉。若改按這些動作細分，就回答了更細的問題，也破壞了原來的四張卡分組。'] },
        { heading: '保持分類層級一致', paragraphs: ['本題採用常見樂器家族，並非完整列出所有樂器或所有聲學分類系統。選項沒有使用鋼琴這類容易引出弦、敲擊動作與鍵盤分組多重討論的樂器。', '檢查替代答案時，要確認每一列使用相同層級：一列按家族，另一列按演奏動作，就混合了標準。把這個習慣帶到下一題：屬性要一致，描述的精細程度也要一致。'] },
      ],
    },
  },
  'es-419': {
    navigation: ['Jugar hoy', 'Cómo jugar', 'Acertijos anteriores', 'Acerca de y contacto', 'Privacidad'],
    skip: 'Ir al contenido', intro: 'Diez tarjetas. Cuatro grupos. Una regla oculta.',
    archiveIntro: 'Una selección de acertijos anteriores de Tensift con el razonamiento de cada respuesta. Elige un tema conocido, intenta clasificar las tarjetas y luego compara tu idea con la explicación. Es una colección seleccionada, no un archivo diario completo.',
    spoiler: 'Esta página contiene la respuesta de un acertijo anterior. El acertijo de hoy es independiente.', answer: 'La clasificación', references: 'Referencias y lecturas', related: 'Sigue explorando',
    contact: 'Contacta al responsable o informa una corrección en GitHub', notFound: 'Página no encontrada',
    howTo: [
      { heading: 'Una regla para las diez tarjetas', paragraphs: ['Tensift es un acertijo diario de clasificación. Diez elementos comparten un tema visible, pero debes descubrir la propiedad que los separa. Colócalos en cuatro filas con uno, dos, tres y cuatro espacios. Las cantidades son pistas, no los nombres de las categorías.', 'Una solución convincente usa el mismo tipo de dato en todas las filas. Si una fila describe un lugar, otra un color y otra un tamaño, quizá estés mezclando reglas. Propón una propiedad y comprueba que sirva para las diez tarjetas.'] },
      { heading: 'Mueve, comprueba y revisa', paragraphs: ['Selecciona una tarjeta y después un espacio, o arrástrala al tablero. Con el teclado, enfoca y selecciona una tarjeta; luego enfoca y activa su destino. Puedes devolver a la bandeja una tarjeta colocada que no esté bloqueada. Mezclar solo cambia el orden de la bandeja.', 'Llena los diez espacios antes de comprobar. Los intentos son ilimitados y el resultado indica cuántas tarjetas están en la fila correcta, sin identificar cuáles. Cambia una parte pequeña entre intentos para aprender algo del nuevo total.'] },
      { heading: 'Un ejemplo de práctica', paragraphs: ['Imagina tarjetas con los números del 0 al 9. Agrupar por el resto al dividir entre 4 produce {3, 7}, {2, 6}, {1, 5, 9} y {0, 4, 8}. La regla es consistente, pero las cantidades son 2, 2, 3 y 3: no encajan en este tablero.', 'Ahora imagina tarjetas A a J con 1, 2, 2, 3, 3, 3, 4, 4, 4 y 4 puntos respectivamente. Agrupar por cantidad de puntos produce A / B C / D E F / G H I J. Encaja en 1 / 2 / 3 / 4 y usa una sola propiedad. Comprueba siempre el significado de la regla y las cantidades.'] },
      { heading: 'Pistas, respuestas y progreso diario', paragraphs: ['Puedes usar una pista para colocar y bloquear una tarjeta en su fila correcta. Úsala para reconsiderar los demás grupos. Revelar la respuesta muestra la clasificación prevista y su explicación cuando quieras dejar de adivinar.', 'El calendario diario usa UTC. El idioma, el tema visual y el progreso se guardan en este navegador. Borrar los datos del sitio elimina ese progreso; no es una copia sincronizada con una cuenta. Compartir genera un texto sin respuestas mediante el menú del dispositivo o el portapapeles.'] },
    ],
    about: [
      { heading: 'Mirar lo conocido desde otro ángulo', paragraphs: ['Tensift propone encontrar una forma consistente de ordenar diez elementos familiares. Las filas de tamaños distintos convierten las cantidades en parte de la deducción. Buscamos un pequeño momento de descubrimiento seguido de una explicación comprensible.', 'El juego está disponible en inglés, chino simplificado y español. La cuenta frobel0520 mantiene el repositorio público en GitHub. No necesitas crear una cuenta para jugar.'] },
      { heading: 'Cómo leer las explicaciones', paragraphs: ['Cada artículo seleccionado incluye las tarjetas, los grupos previstos, un camino de razonamiento y alternativas que pueden confundir. Las referencias aportan contexto; no avalan Tensift ni certifican que cada acertijo tenga una sola solución.', 'Algunas clasificaciones usan convenciones cotidianas, no una taxonomía científica completa. Indicamos esa diferencia cuando corresponde. Esta selección no implica que todos los acertijos programados hayan superado pruebas independientes a ciegas.'] },
      { heading: 'Correcciones y contacto', paragraphs: ['Si una tarjeta admite dos grupos razonables, envía la fecha, el idioma, la clasificación alternativa completa y el motivo. Un contraejemplo concreto ayuda más que una puntuación. Para errores técnicos, incluye el navegador y los pasos para reproducirlos.', 'Puedes contactar al responsable mediante Issues en GitHub. Los reportes son públicos: no incluyas contraseñas, datos privados de contacto ni otra información sensible.'] },
    ],
    privacy: [
      { heading: 'Datos en tu navegador', paragraphs: ['Actualizado el 19 de septiembre de 2026. Tensift guarda idioma, tema y progreso en localStorage de tu dispositivo. Incluye posiciones, intentos y uso de pistas. Puedes borrarlos con los controles de datos del sitio del navegador; también perderás tus preferencias y progreso.', 'El juego no ofrece cuentas ni sincronización entre dispositivos. El código de la aplicación no incorpora actualmente un servicio de analítica.'] },
      { heading: 'Solicitudes necesarias para jugar', paragraphs: ['Al cargar un acertijo, comprobar una clasificación o pedir una pista o respuesta, el navegador envía los datos pertinentes a los servidores de Tensift alojados en Cloudflare. Las solicitudes de pista y respuesta incluyen un identificador de sesión aleatorio. El servidor guarda comprobantes con fecha de vencimiento para manejar solicitudes repetidas.', 'Cloudflare recibe información normal de conexión, como la dirección IP y las cabeceras, al servir el sitio. Su tratamiento de alojamiento y seguridad se rige por su política de privacidad. Tensift también utiliza un servicio de estado de mantenimiento en Cloudflare; las cookies de acceso de vista previa sirven para ese acceso, no para crear perfiles publicitarios.'] },
      { heading: 'Publicidad y enlaces externos', paragraphs: ['La publicación de anuncios está desactivada actualmente. Se conservan los metadatos de propiedad de AdSense y el punto de verificación ads.txt, que por sí solos no cargan scripts publicitarios. Antes de activar anuncios deberán actualizarse este aviso y los controles de consentimiento necesarios.', 'Cuando está habilitada, la publicidad de Google puede utilizar cookies u otros identificadores y procesar direcciones IP e información de uso para mostrar y medir anuncios y, cuando corresponda, personalizarlos. Consulta la información de privacidad de Google enlazada abajo.', 'Los enlaces de referencia o contacto llevan a otros proveedores. Tú inicias la función de compartir mediante el menú del dispositivo o el portapapeles. Revisa el contenido antes de enviarlo. Para consultas, contacta al responsable mediante el repositorio público sin publicar datos personales sensibles.'] },
    ],
    articles: {
      countries: [
        { heading: 'Encuentra la escala geográfica', paragraphs: ['Francia, Alemania, Italia y España ofrecen un grupo de cuatro sin recurrir a monedas, idiomas o población. Brasil y Argentina sugieren otra asociación geográfica. Juntas, estas observaciones hacen que valga la pena probar una regla por continentes.', 'Australia ocupa entonces la fila individual y Canadá, México y Estados Unidos completan la de tres. Lo decisivo es que una sola convención explica las diez tarjetas con las cantidades exactas, no simplemente que algunos países estén relacionados.'] },
        { heading: 'Por qué el idioma puede despistar', paragraphs: ['Un idioma compartido conecta ciertos países, pero no produce necesariamente la partición completa. Si tu hipótesis explica unas pocas tarjetas y necesita excepciones para las demás, compárala con una que abarque todo el tablero.', 'Usa la fila individual como comprobación. Casi cualquier país puede parecer único si eliges un dato suficientemente específico. Esa singularidad solo ayuda cuando la misma propiedad organiza los otros nueve.'] },
        { heading: 'La convención de esta respuesta', paragraphs: ['Aquí se usa Oceanía y se separan América del Norte y América del Sur. Otras tradiciones educativas cuentan los continentes de otra manera. México pertenece a América del Norte en este ejercicio; Latinoamérica es otra agrupación.', 'La tabla M49 de la ONU sirve para consultar regiones y ubicaciones, pero sus subdivisiones estadísticas no equivalen exactamente a las cuatro categorías del juego. Conviene distinguir la escala y la convención de cada clasificación.'] },
      ],
      animals: [
        { heading: 'Qué animal es, no dónde vive', paragraphs: ['El delfín y el pingüino ponen a prueba una hipótesis. Reunir a los que nadan parece natural, pero mezcla animales con características biológicas diferentes. Busca una clasificación que siga siendo útil cuando cambia el entorno del animal.', 'Los grupos habituales de este ejercicio dejan a la rana sola, al cocodrilo y la tortuga en la pareja, y al águila, el pingüino y el loro en el trío. Comprueba también la propiedad de los cuatro restantes: “lo que sobra” no constituye una regla.'] },
        { heading: 'Las tarjetas que obligan a reconsiderar', paragraphs: ['El pingüino se agrupa con las demás aves aunque no vuele. El delfín se agrupa con los demás mamíferos aunque viva en el agua. Una conducta visible y la categoría utilizada son pistas diferentes.', 'Formula tu regla como una pregunta completa: “¿cómo se mueve?” no equivale a “¿qué tipo de animal es?”. Si una tarjeta se resiste, reconsidera la pregunta antes de declararla una excepción.'] },
        { heading: 'Una clasificación simplificada', paragraphs: ['La respuesta utiliza grupos escolares conocidos, no un árbol evolutivo completo. La filogenia moderna sitúa a las aves dentro del linaje de los reptiles; aquí se usa el sentido tradicional de reptiles no avianos.', 'La convención debe quedar clara incluso cuando los nombres resultan familiares. Si encuentras otra regla consistente que conserve 1 / 2 / 3 / 4, envía la clasificación completa para poder examinarla.'] },
      ],
      instruments: [
        { heading: 'Piensa en el origen del sonido', paragraphs: ['El contraste entre el tambor y los instrumentos con cuerdas ofrece un buen comienzo. El tambor queda solo; violín, guitarra, violonchelo y arpa llenan la fila de cuatro. Las cantidades sugieren familias instrumentales conocidas.', 'Los cinco restantes utilizan aire, pero no existe una fila de cinco. Trompeta y trombón forman la pareja; flauta, clarinete y oboe, el trío. La regla debe explicar esa división, no limitarse a forzar tarjetas para llenar espacios.'] },
        { heading: 'El material puede confundir', paragraphs: ['Una flauta metálica no pasa a la familia de los metales solo por su material. En esta convención importa más cómo se produce el sonido que la sustancia del cuerpo del instrumento.', 'La fila de cuerdas incluye técnicas distintas: guitarra y arpa suelen pulsarse; violín y violonchelo suelen tocarse con arco. Dividir por esas acciones respondería a una pregunta más específica y rompería el grupo de cuatro.'] },
        { heading: 'Mantén el mismo nivel de detalle', paragraphs: ['Son familias habituales, no un inventario de todos los instrumentos ni de todos los sistemas acústicos. La selección evita casos como el piano, que puede provocar discusiones sobre cuerdas, percusión y teclados.', 'Al evaluar otra solución, comprueba el nivel de descripción. Una fila por familia y otra por técnica mezclan criterios. Lleva esta comprobación al siguiente acertijo: conserva tanto la propiedad como su grado de detalle.'] },
      ],
    },
  },
};
