import type { Locale } from '../../shared/contracts';

export interface Section {
  readonly heading: string;
  readonly paragraphs: readonly string[];
}

export interface EditorialCopy {
  readonly navigation: readonly [string, string, string, string, string];
  readonly skip: string;
  readonly intro: string;
  readonly archiveIntro: string;
  readonly spoiler: string;
  readonly answer: string;
  readonly references: string;
  readonly related: string;
  readonly contact: string;
  readonly notFound: string;
  readonly howTo: readonly Section[];
  readonly about: readonly Section[];
  readonly privacy: readonly Section[];
  readonly articles: Readonly<Record<string, readonly Section[]>>;
}

export const editorialCopy: Readonly<Record<Locale, EditorialCopy>> = {
  en: {
    navigation: ['Play today', 'How to play', 'Past puzzles', 'About & contact', 'Privacy'],
    skip: 'Skip to content',
    intro: 'Ten cards. Four groups. One hidden rule.',
    archiveIntro: 'Selected past Tensift puzzles, with the reasoning behind each answer. Start with a topic you recognize, try your own grouping, then compare your reasoning with the explanation. This is a curated collection, not a complete daily archive.',
    spoiler: 'This page contains the answer to a past puzzle. Today’s puzzle is separate.',
    answer: 'The grouping', references: 'References and further reading', related: 'Keep exploring',
    contact: 'Contact the maintainer or report a correction on GitHub', notFound: 'Page not found',
    howTo: [
      { heading: 'One rule for all ten cards', paragraphs: ['Tensift is a daily classification puzzle. You see ten items connected by a broad topic, but the property that separates them is hidden. Arrange every card into four rows with one, two, three and four spaces. The row sizes are clues to the distribution, not names for the categories.', 'A convincing solution uses the same kind of fact across all four rows. If one row describes where something is found, another describes its color and a third describes its size, step back: you may be mixing rules. First propose a property, then check whether it explains all ten cards.'] },
      { heading: 'Move, check and revise', paragraphs: ['Select a card and then select an empty space, or drag the card onto the board. With a keyboard, focus a card, select it, then focus and activate a destination. A placed, unlocked card can be returned to the tray. Shuffle changes the tray order; it does not change the answer.', 'Fill all ten spaces before checking. Checks are unlimited, and the feedback reports the total number of correctly grouped cards. It does not identify which individual cards are correct. Change a small part of your arrangement between checks so that the new total tells you something useful.'] },
      { heading: 'A worked practice example', paragraphs: ['Imagine ten cards labeled 0 through 9. A possible rule is the remainder after dividing by 4. The four groups are {3, 7}, {2, 6}, {1, 5, 9}, and {0, 4, 8}. Their sizes are 2, 2, 3, 3, so this rule cannot fit a Tensift board—even though it classifies every card consistently.', 'Now imagine cards A, B, C, D, E, F, G, H, I and J marked respectively with 1, 2, 2, 3, 3, 3, 4, 4, 4 and 4 dots. Grouping by dot count produces A / B C / D E F / G H I J. That fits 1 / 2 / 3 / 4 and applies one property everywhere. The lesson is to test both the meaning of your rule and the group counts.'] },
      { heading: 'Hints, answers and daily play', paragraphs: ['One hint can place and lock a card in its correct row. Use that fixed card to reconsider the surrounding groups. Reveal answer opens the intended grouping and explanation; it is available whenever you want to stop guessing. There is no penalty for learning from an explanation.', 'The daily schedule uses UTC. Language and theme preferences, along with saved puzzle progress, are stored in this browser. Clearing site data removes that local progress; it is not an account-based backup. Sharing a result sends a text summary without the answer, through your device’s share sheet or clipboard.'] },
    ],
    about: [
      { heading: 'A small puzzle about changing perspective', paragraphs: ['Tensift asks you to find a useful way to sort familiar things. The ten-card format keeps the board compact, while the unequal row sizes make the category counts part of the deduction. The aim is a short moment of discovery, followed by an explanation you can understand.', 'The game is available in English, Simplified Chinese and Spanish. The public source repository is maintained under the GitHub account frobel0520. You can play without creating an account.'] },
      { heading: 'How to read our explanations', paragraphs: ['Each selected archive page includes the original items, intended groups, a reasoning path and a discussion of misleading alternatives. References provide background; they do not endorse Tensift or independently certify that a puzzle has only one answer.', 'Some classifications use an everyday convention rather than a scientific taxonomy. We state that distinction where it matters. The archive is an editorial selection and does not imply that every scheduled puzzle has passed independent blind playtesting.'] },
      { heading: 'Corrections and contact', paragraphs: ['If a card has two plausible homes, tell us the puzzle date, language, proposed grouping and why it fits. A specific counterexample is more useful than a score alone. For a technical bug, include your browser and the steps that led to the problem.', 'Use the repository’s Issues page to reach the maintainer. GitHub issues are public: do not include passwords, private contact details or other sensitive information.'] },
    ],
    privacy: [
      { heading: 'What stays in your browser', paragraphs: ['Updated 19 September 2026. Tensift stores language, theme and puzzle progress in localStorage on your device. Progress includes card placements, attempts and hint usage. You can remove it with your browser’s site-data controls. This also removes saved preferences and progress.', 'The game does not offer user accounts or cross-device synchronization. Its application code does not currently include an analytics service.'] },
      { heading: 'Requests needed to operate the game', paragraphs: ['When you load a puzzle or request a check, hint or answer, your browser sends the relevant game data to Tensift’s server endpoints hosted on Cloudflare. Hint and reveal requests include a randomly generated client-session identifier. The server stores action receipts with expiry timestamps to handle repeated requests.', 'Cloudflare receives ordinary connection information, such as your IP address and request headers, when serving the site. Hosting and security processing are governed by Cloudflare’s privacy policy. Tensift also uses a maintenance-status service operated through Cloudflare; any preview-access cookie is for maintenance access, not an advertising profile.'] },
      { heading: 'Advertising and external links', paragraphs: ['Ad serving is currently disabled on Tensift pages. AdSense ownership metadata and the ads.txt verification endpoint remain, but they do not by themselves load an advertising script. If advertising is enabled in the future, this notice and any required consent controls must be updated before ad requests begin.', 'Google advertising, when enabled, can use cookies or other identifiers and process IP addresses and usage information for ad delivery, measurement and, where applicable, personalization. Read Google’s partner-site privacy information below for details.', 'Following a reference or contact link takes you to another provider. Sharing is initiated by you through your device’s share sheet or clipboard. Please review what you share. For questions or corrections, contact the maintainer through the public GitHub repository without posting sensitive personal data.'] },
    ],
    articles: {
      countries: [
        { heading: 'Find the scale of the question', paragraphs: ['Start with the four European countries. They form a plausible four-card row without needing a detail such as currency, language or population. Brazil and Argentina suggest a second geographic group. Together, those observations make a continent-based interpretation worth testing.', 'Australia then occupies the one-card row, leaving Canada, Mexico and the United States together. Count every group before committing: the useful evidence is that a single geographic convention accounts for all ten cards in exactly the required sizes.'] },
        { heading: 'Why language is a tempting wrong turn', paragraphs: ['Shared languages can connect some of these countries, but that hypothesis does not produce the same complete partition. A partial association is not enough: if your rule works for three cards and leaves several exceptions, compare it with a rule that handles the entire board.', 'Treat the one-card row as a cross-check, not your first certainty. Almost any country can be made unique by choosing a sufficiently specific fact. It becomes meaningful only when the same property organizes the other nine.'] },
        { heading: 'A note on geographic conventions', paragraphs: ['This puzzle uses Oceania and separates North America from South America. Other educational traditions count continents differently. Mexico belongs in the North America row here; “Latin America” is a different grouping and would change the problem.', 'The linked UN M49 table is a reference for geographic regions and country placement, not a claim that all its statistical subdivisions equal this puzzle’s four categories. Read the rule with the stated convention in mind rather than assuming every regional label is interchangeable.'] },
      ],
      animals: [
        { heading: 'Test identity, not where an animal lives', paragraphs: ['The dolphin and penguin are useful stress tests for a proposed rule. Grouping everything that swims together feels natural, but it mixes animals with different biological characteristics. Try a classification that remains useful when an animal changes its surroundings.', 'The intended everyday vertebrate groups give the frog a one-card row, crocodile and turtle a two-card row, and eagle, penguin and parrot a three-card row. The remaining four belong together. Check the entire partition rather than treating “the leftovers” as a separate rule.'] },
        { heading: 'What the surprising cards teach', paragraphs: ['A penguin belongs with the other birds despite not flying. A dolphin belongs with the other mammals despite living in water. These cards expose the difference between a visible behavior and the category the puzzle is using.', 'A useful solving habit is to name your rule aloud: “how it moves” and “what kind of animal it is” are different questions. When one card keeps resisting a grouping, reconsider the question before assuming the card is an exception.'] },
        { heading: 'The limits of this simplified classification', paragraphs: ['The answer uses familiar school-level group names. It is not a complete evolutionary tree: modern phylogenetic treatments place birds within the reptile lineage. Here, “reptiles” means the conventional non-avian group used in the exercise.', 'That qualification matters because a puzzle needs a clear convention as well as familiar examples. If you find an alternative that applies consistently to all ten animals and preserves 1 / 2 / 3 / 4, report the full grouping so it can be examined.'] },
      ],
      instruments: [
        { heading: 'Listen to how the sound begins', paragraphs: ['The most useful starting contrast is between the drum and the instruments with vibrating strings. The drum stands alone in this selection, while violin, guitar, cello and harp fill the four-card row. Those counts suggest a familiar instrument-family convention.', 'The remaining five all involve air, but one five-card group will not fit. Trumpet and trombone form the pair; flute, clarinet and oboe form the trio. A good rule explains why that split is meaningful, rather than simply using row sizes to force unrelated cards together.'] },
        { heading: 'Why the material can mislead', paragraphs: ['A metal flute does not move into the brass family just because of its material. In this convention, the way sound is produced matters more than the substance of the instrument’s body. That is why “made of metal” is a poor replacement for the intended rule.', 'The string row also contains different playing techniques. Guitar and harp are commonly plucked; violin and cello are commonly bowed. Separating by those techniques would answer a narrower question and would break the four-card group.'] },
        { heading: 'Use the convention at the right level', paragraphs: ['These are familiar instrument families, not a comprehensive catalog of every instrument or every acoustical classification system. The selected cards avoid instruments such as the piano, which can invite discussion about strings, striking actions and keyboard groupings.', 'When evaluating an alternative answer, ask whether the same level of description applies to every row. A family in one row and a playing technique in another would mix levels. Carry this check into the next puzzle: keep both the property and its level of detail consistent.'] },
      ],
    },
  },
  'zh-Hans': {
    navigation: ['今日谜题', '玩法指南', '往期谜题', '关于与联系', '隐私说明'],
    skip: '跳到正文', intro: '十张卡片。四个分组。一个隐藏规则。',
    archiveIntro: '这里精选已经结束的 Tensift 谜题，解释答案背后的思路。先选一个熟悉的主题，尝试自己的分类，再对照解析。这是精选题解集，并非完整的每日存档。',
    spoiler: '本页包含往期谜题答案，与今日谜题分开。', answer: '完整分组', references: '参考资料与延伸阅读', related: '继续探索',
    contact: '在 GitHub 联系维护者或提交更正', notFound: '找不到这个页面',
    howTo: [
      { heading: '用同一条规则解释十张卡', paragraphs: ['Tensift 是每日分类谜题。十张卡片共享一个可见主题，但真正的分类角度需要你发现。把它们放进容量为 1、2、3、4 的四行。数字只告诉你每组的数量，不会直接告诉你组名。', '一个合理的解法应该对所有分组使用同一种事实。如果一行按地点，另一行按颜色，第三行又按大小，就可能混用了规则。先提出分类角度，再检查它是否能解释全部十张卡。'] },
      { heading: '移动、检查与修正', paragraphs: ['点击卡片，再点击空格即可放置，也可以拖曳。使用键盘时，先聚焦并选中卡片，再聚焦并启用目标格。已经放置但没有锁定的卡片可以退回待选区。「打乱」只改变待选卡片顺序，不改变答案。', '填满十个格子后才能检查，次数不限。反馈给出正确归类的总数，不会指出具体哪张正确。每次只调整一小部分，再比较正确数量，通常比一次全部重排更容易获得线索。'] },
      { heading: '用一个练习理解数量线索', paragraphs: ['假设十张卡片是数字 0 到 9，按除以 4 的余数分类，可以得到 {3, 7}、{2, 6}、{1, 5, 9}、{0, 4, 8}。规则虽然一致，数量却是 2、2、3、3，不能放进 Tensift 的棋盘。规则合理与数量吻合，两者都必须满足。', '再假设 A 到 J 十张卡片分别标有 1、2、2、3、3、3、4、4、4、4 个圆点。按圆点数量分类，就得到 A / B C / D E F / G H I J，正好符合 1 / 2 / 3 / 4。实际谜题会隐藏这个角度，但验证方法相同。'] },
      { heading: '提示、揭晓与每日进度', paragraphs: ['每题有一次提示，会把一张卡放到正确的行并锁定。你可以用它重新检查其他分组。想停止猜测时，随时选择「显示答案」，阅读预设分组与解释。看懂解析也是游戏的一部分。', '每日排程使用 UTC。语言、主题及谜题进度保存在当前浏览器，清除网站数据会删除这些记录，并不会同步到其他装置。分享功能通过装置分享菜单或剪贴板提供不含答案的文字结果。'] },
    ],
    about: [
      { heading: '练习换个角度看熟悉的事物', paragraphs: ['Tensift 把十个熟悉项目放在同一个棋盘上，邀请你寻找一致的分类方法。四行不相等的容量，让数量本身也成为推理线索。我们希望每题带来一次短暂的发现，也提供能读懂的解释。', '游戏支持英语、简体中文和西班牙语，无需注册。公开源代码由 GitHub 账号 frobel0520 维护。'] },
      { heading: '如何阅读题解', paragraphs: ['精选题解包含原始卡片、预设分组、推理过程及容易混淆的其他角度。参考资料用于补充背景，不代表来源机构为 Tensift 背书，也不代表它们验证过答案的唯一性。', '有些分类采用日常惯例，而不是完整的科学分类系统；我们会在相关解析中说明。精选题解不代表所有排程题目均已通过独立盲测。'] },
      { heading: '更正与联系', paragraphs: ['如果某张卡有两个合理归属，请提供题目日期、语言、完整的替代分组与理由。一个具体反例比单纯的分数更能帮助改进。报告技术问题时，请附上浏览器名称和重现步骤。', '你可以通过项目的 GitHub Issues 联系维护者。Issue 是公开的，请不要提供密码、私人联系方式或其他敏感资料。'] },
    ],
    privacy: [
      { heading: '保存在浏览器中的资料', paragraphs: ['更新日期：2026 年 9 月 19 日。Tensift 使用装置上的 localStorage 保存语言、主题及谜题进度，包括卡片位置、尝试次数和提示使用情况。你可以通过浏览器的网站数据设置删除它们，同时也会失去已保存的偏好与进度。', '游戏目前没有账号及跨装置同步功能，应用程序代码目前没有接入统计分析服务。'] },
      { heading: '游戏运行所需的请求', paragraphs: ['载入谜题、检查排列、请求提示或揭晓答案时，浏览器会把相关游戏资料发送到部署在 Cloudflare 的 Tensift 服务器接口。提示及揭晓请求带有随机产生的客户端会话标识；服务器保存带过期时间的操作记录，以处理重复请求。', 'Cloudflare 提供网站服务时会接收 IP 地址及请求标头等通常的连接信息，其托管与安全处理适用 Cloudflare 隐私政策。Tensift 也使用经 Cloudflare 运行的维护状态服务；维护预览的访问 Cookie 用于访问控制，而非广告画像。'] },
      { heading: '广告与外部链接', paragraphs: ['Tensift 页面目前停用广告投放。AdSense 所有权元数据与 ads.txt 验证接口仍然保留，但它们本身不会载入广告脚本。未来启用广告之前，必须更新此说明并配置所需的同意控制。', '启用后，Google 广告可能使用 Cookie 或其他标识，并处理 IP 地址与使用信息，用于广告投放、衡量及适用情况下的个性化。详情请参阅下方 Google 合作网站隐私说明。', '点击参考资料或联系链接会前往其他服务。分享由你通过装置菜单或剪贴板主动发起，请检查分享内容。如有问题，可通过公开 GitHub 项目联系维护者，但请勿公开敏感个人资料。'] },
    ],
    articles: {
      countries: [
        { heading: '先找对地理尺度', paragraphs: ['法国、德国、意大利和西班牙可以组成四张卡的一组，无需先猜货币、人口或语言。巴西与阿根廷又提示了另一组地理关联。把两条线索放在一起，按洲划分就值得尝试。', '接着，澳大利亚进入单张卡的行，加拿大、墨西哥和美国组成三张卡的行。真正有用的证据不是某两国有关联，而是同一种地理惯例能让全部十张卡恰好符合四行容量。'] },
        { heading: '为什么语言容易让人走偏', paragraphs: ['共同语言能够连接部分国家，却不一定产生相同的完整划分。如果一个想法只能解释三张卡，其他项目却需要不断增加例外，就应该拿它与能够解释整张棋盘的规则比较。', '单张卡的行更适合用来验证，而不是最先认定。只要挑选足够特殊的事实，几乎每个国家都能显得独一无二。只有当同一属性也能整理其他九张卡时，这种独特性才有意义。'] },
        { heading: '这里采用的地理惯例', paragraphs: ['本题使用「大洋洲」，并将北美洲与南美洲分开。不同教育传统对洲的数量可能有不同处理。这里墨西哥属于北美洲；「拉丁美洲」是另一种划分，不能直接替换。', '联合国 M49 表可用于查阅地理区域和国家位置，但其统计分区层级并不等同于本题的四个组名。阅读资料时，要注意分类所采用的范围与层级。'] },
      ],
      animals: [
        { heading: '先问是什么动物，而不是住在哪里', paragraphs: ['海豚和企鹅特别适合检验你的规则。把会游泳的动物放在一起很直觉，却混合了不同生物类别。试着寻找一种不会随着活动地点改变而改变的分类方式。', '本题采用的常见脊椎动物分组让青蛙单独一行，鳄鱼与乌龟占两格，鹰、企鹅与鹦鹉占三格，其余四种归为一组。必须验证最后一组的共同点，而不能只把它当作「剩下的卡片」。'] },
        { heading: '最容易误放的两张卡', paragraphs: ['企鹅虽然不会飞，仍与其他鸟类放在一起；海豚虽然生活在水中，仍与其他哺乳动物放在一起。它们提示我们：可见行为与本题采用的类别，是两种不同线索。', '解题时不妨把规则说成完整问题：「如何移动？」和「属于哪类动物？」并不相同。遇到一张卡总是放不进去时，先检查自己问的问题，别急着把它当成例外。'] },
        { heading: '简化分类的边界', paragraphs: ['这里使用熟悉的学校教育分组，不是完整的演化树。现代系统发育分类会把鸟类放在爬行动物演化支系之内；本题的「爬行动物」采用日常练习中不含鸟类的传统用法。', '熟悉的名词仍然需要明确惯例。如果你找到另一种适用于十张卡、同时符合 1 / 2 / 3 / 4 的分类，请提交完整分组，让我们能够实际检查歧义。'] },
      ],
      instruments: [
        { heading: '从声音如何产生开始', paragraphs: ['鼓与带弦乐器的对比是很好的起点。鼓在这组卡片中单独成组，小提琴、吉他、大提琴和竖琴恰好占满四格。这些数量提示了熟悉的乐器家族划分。', '剩下五种都与气流有关，但棋盘没有五格的行。小号和长号组成两张卡的一组，长笛、单簧管和双簧管组成三张卡的一组。规则应该解释这种拆分，而不是只为填满格子硬凑。'] },
        { heading: '材质为什么会误导', paragraphs: ['金属制的长笛不会因为材质就被放进铜管组。在本题采用的惯例中，发声方式比乐器外壳的材料更重要，因此「是否由金属制成」不是可靠的替代规则。', '四张弦乐器卡片也包含不同演奏方式：吉他、竖琴常用拨弦，小提琴、大提琴常用弓拉。若改按这些动作细分，就回答了更细的问题，也破坏了原来的四张卡分组。'] },
        { heading: '保持分类层级一致', paragraphs: ['本题采用常见乐器家族，并非完整列出所有乐器或所有声学分类系统。选项没有使用钢琴这类容易引出弦、敲击动作与键盘分组多重讨论的乐器。', '检查替代答案时，要确认每一行使用相同层级：一行按家族，另一行按演奏动作，就混合了标准。把这个习惯带到下一题：属性要一致，描述的精细程度也要一致。'] },
      ],
    },
  },
  'es-419': {
    navigation: ['Jugar hoy', 'Cómo jugar', 'Acertijos anteriores', 'Acerca de y contacto', 'Privacidad'],
    skip: 'Ir al contenido', intro: 'Diez tarjetas. Cuatro grupos. Una regla oculta.',
    archiveIntro: 'Una selección de acertijos anteriores de Tensift con el razonamiento de cada respuesta. Elige un tema conocido, intenta clasificar las tarjetas y luego compara tu idea con la explicación. Es una colección seleccionada, no un archivo diario completo.',
    spoiler: 'Esta página contiene la respuesta de un acertijo anterior. El acertijo de hoy es independiente.', answer: 'La clasificación', references: 'Referencias y lecturas', related: 'Sigue explorando',
    contact: 'Contacta al responsable o informa una corrección en GitHub', notFound: 'Página no encontrada',
    howTo: [
      { heading: 'Una regla para las diez tarjetas', paragraphs: ['Tensift es un acertijo diario de clasificación. Diez elementos comparten un tema visible, pero debes descubrir la propiedad que los separa. Colócalos en cuatro filas con uno, dos, tres y cuatro espacios. Las cantidades son pistas, no los nombres de las categorías.', 'Una solución convincente usa el mismo tipo de dato en todas las filas. Si una fila describe un lugar, otra un color y otra un tamaño, quizá estés mezclando reglas. Propón una propiedad y comprueba que sirva para las diez tarjetas.'] },
      { heading: 'Mueve, comprueba y revisa', paragraphs: ['Selecciona una tarjeta y después un espacio, o arrástrala al tablero. Con el teclado, enfoca y selecciona una tarjeta; luego enfoca y activa su destino. Puedes devolver a la bandeja una tarjeta colocada que no esté bloqueada. Mezclar solo cambia el orden de la bandeja.', 'Llena los diez espacios antes de comprobar. Los intentos son ilimitados y el resultado indica cuántas tarjetas están en la fila correcta, sin identificar cuáles. Cambia una parte pequeña entre intentos para aprender algo del nuevo total.'] },
      { heading: 'Un ejemplo de práctica', paragraphs: ['Imagina tarjetas con los números del 0 al 9. Agrupar por el resto al dividir entre 4 produce {3, 7}, {2, 6}, {1, 5, 9} y {0, 4, 8}. La regla es consistente, pero las cantidades son 2, 2, 3 y 3: no encajan en este tablero.', 'Ahora imagina tarjetas A a J con 1, 2, 2, 3, 3, 3, 4, 4, 4 y 4 puntos respectivamente. Agrupar por cantidad de puntos produce A / B C / D E F / G H I J. Encaja en 1 / 2 / 3 / 4 y usa una sola propiedad. Comprueba siempre el significado de la regla y las cantidades.'] },
      { heading: 'Pistas, respuestas y progreso diario', paragraphs: ['Puedes usar una pista para colocar y bloquear una tarjeta en su fila correcta. Úsala para reconsiderar los demás grupos. Revelar la respuesta muestra la clasificación prevista y su explicación cuando quieras dejar de adivinar.', 'El calendario diario usa UTC. El idioma, el tema visual y el progreso se guardan en este navegador. Borrar los datos del sitio elimina ese progreso; no es una copia sincronizada con una cuenta. Compartir genera un texto sin respuestas mediante el menú del dispositivo o el portapapeles.'] },
    ],
    about: [
      { heading: 'Mirar lo conocido desde otro ángulo', paragraphs: ['Tensift propone encontrar una forma consistente de ordenar diez elementos familiares. Las filas de tamaños distintos convierten las cantidades en parte de la deducción. Buscamos un pequeño momento de descubrimiento seguido de una explicación comprensible.', 'El juego está disponible en inglés, chino simplificado y español. La cuenta frobel0520 mantiene el repositorio público en GitHub. No necesitas crear una cuenta para jugar.'] },
      { heading: 'Cómo leer las explicaciones', paragraphs: ['Cada artículo seleccionado incluye las tarjetas, los grupos previstos, un camino de razonamiento y alternativas que pueden confundir. Las referencias aportan contexto; no avalan Tensift ni certifican que cada acertijo tenga una sola solución.', 'Algunas clasificaciones usan convenciones cotidianas, no una taxonomía científica completa. Indicamos esa diferencia cuando corresponde. Esta selección no implica que todos los acertijos programados hayan superado pruebas independientes a ciegas.'] },
      { heading: 'Correcciones y contacto', paragraphs: ['Si una tarjeta admite dos grupos razonables, envía la fecha, el idioma, la clasificación alternativa completa y el motivo. Un contraejemplo concreto ayuda más que una puntuación. Para errores técnicos, incluye el navegador y los pasos para reproducirlos.', 'Puedes contactar al responsable mediante Issues en GitHub. Los reportes son públicos: no incluyas contraseñas, datos privados de contacto ni otra información sensible.'] },
    ],
    privacy: [
      { heading: 'Datos en tu navegador', paragraphs: ['Actualizado el 19 de septiembre de 2026. Tensift guarda idioma, tema y progreso en localStorage de tu dispositivo. Incluye posiciones, intentos y uso de pistas. Puedes borrarlos con los controles de datos del sitio del navegador; también perderás tus preferencias y progreso.', 'El juego no ofrece cuentas ni sincronización entre dispositivos. El código de la aplicación no incorpora actualmente un servicio de analítica.'] },
      { heading: 'Solicitudes necesarias para jugar', paragraphs: ['Al cargar un acertijo, comprobar una clasificación o pedir una pista o respuesta, el navegador envía los datos pertinentes a los servidores de Tensift alojados en Cloudflare. Las solicitudes de pista y respuesta incluyen un identificador de sesión aleatorio. El servidor guarda comprobantes con fecha de vencimiento para manejar solicitudes repetidas.', 'Cloudflare recibe información normal de conexión, como la dirección IP y las cabeceras, al servir el sitio. Su tratamiento de alojamiento y seguridad se rige por su política de privacidad. Tensift también utiliza un servicio de estado de mantenimiento en Cloudflare; las cookies de acceso de vista previa sirven para ese acceso, no para crear perfiles publicitarios.'] },
      { heading: 'Publicidad y enlaces externos', paragraphs: ['La publicación de anuncios está desactivada actualmente. Se conservan los metadatos de propiedad de AdSense y el punto de verificación ads.txt, que por sí solos no cargan scripts publicitarios. Antes de activar anuncios deberán actualizarse este aviso y los controles de consentimiento necesarios.', 'Cuando está habilitada, la publicidad de Google puede utilizar cookies u otros identificadores y procesar direcciones IP e información de uso para mostrar y medir anuncios y, cuando corresponda, personalizarlos. Consulta la información de privacidad de Google enlazada abajo.', 'Los enlaces de referencia o contacto llevan a otros proveedores. Tú inicias la función de compartir mediante el menú del dispositivo o el portapapeles. Revisa el contenido antes de enviarlo. Para consultas, contacta al responsable mediante el repositorio público sin publicar datos personales sensibles.'] },
    ],
    articles: {
      countries: [
        { heading: 'Encuentra la escala geográfica', paragraphs: ['Francia, Alemania, Italia y España ofrecen un grupo de cuatro sin recurrir a monedas, idiomas o población. Brasil y Argentina sugieren otra asociación geográfica. Juntas, estas observaciones hacen que valga la pena probar una regla por continentes.', 'Australia ocupa entonces la fila individual y Canadá, México y Estados Unidos completan la de tres. Lo decisivo es que una sola convención explica las diez tarjetas con las cantidades exactas, no simplemente que algunos países estén relacionados.'] },
        { heading: 'Por qué el idioma puede despistar', paragraphs: ['Un idioma compartido conecta ciertos países, pero no produce necesariamente la partición completa. Si tu hipótesis explica unas pocas tarjetas y necesita excepciones para las demás, compárala con una que abarque todo el tablero.', 'Usa la fila individual como comprobación. Casi cualquier país puede parecer único si eliges un dato suficientemente específico. Esa singularidad solo ayuda cuando la misma propiedad organiza los otros nueve.'] },
        { heading: 'La convención de esta respuesta', paragraphs: ['Aquí se usa Oceanía y se separan América del Norte y América del Sur. Otras tradiciones educativas cuentan los continentes de otra manera. México pertenece a América del Norte en este ejercicio; Latinoamérica es otra agrupación.', 'La tabla M49 de la ONU sirve para consultar regiones y ubicaciones, pero sus subdivisiones estadísticas no equivalen exactamente a las cuatro categorías del juego. Conviene distinguir la escala y la convención de cada clasificación.'] },
      ],
      animals: [
        { heading: 'Qué animal es, no dónde vive', paragraphs: ['El delfín y el pingüino ponen a prueba una hipótesis. Reunir a los que nadan parece natural, pero mezcla animales con características biológicas diferentes. Busca una clasificación que siga siendo útil cuando cambia el entorno del animal.', 'Los grupos habituales de este ejercicio dejan a la rana sola, al cocodrilo y la tortuga en la pareja, y al águila, el pingüino y el loro en el trío. Comprueba también la propiedad de los cuatro restantes: “lo que sobra” no constituye una regla.'] },
        { heading: 'Las tarjetas que obligan a reconsiderar', paragraphs: ['El pingüino se agrupa con las demás aves aunque no vuele. El delfín se agrupa con los demás mamíferos aunque viva en el agua. Una conducta visible y la categoría utilizada son pistas diferentes.', 'Formula tu regla como una pregunta completa: “¿cómo se mueve?” no equivale a “¿qué tipo de animal es?”. Si una tarjeta se resiste, reconsidera la pregunta antes de declararla una excepción.'] },
        { heading: 'Una clasificación simplificada', paragraphs: ['La respuesta utiliza grupos escolares conocidos, no un árbol evolutivo completo. La filogenia moderna sitúa a las aves dentro del linaje de los reptiles; aquí se usa el sentido tradicional de reptiles no avianos.', 'La convención debe quedar clara incluso cuando los nombres resultan familiares. Si encuentras otra regla consistente que conserve 1 / 2 / 3 / 4, envía la clasificación completa para poder examinarla.'] },
      ],
      instruments: [
        { heading: 'Piensa en el origen del sonido', paragraphs: ['El contraste entre el tambor y los instrumentos con cuerdas ofrece un buen comienzo. El tambor queda solo; violín, guitarra, violonchelo y arpa llenan la fila de cuatro. Las cantidades sugieren familias instrumentales conocidas.', 'Los cinco restantes utilizan aire, pero no existe una fila de cinco. Trompeta y trombón forman la pareja; flauta, clarinete y oboe, el trío. La regla debe explicar esa división, no limitarse a forzar tarjetas para llenar espacios.'] },
        { heading: 'El material puede confundir', paragraphs: ['Una flauta metálica no pasa a la familia de los metales solo por su material. En esta convención importa más cómo se produce el sonido que la sustancia del cuerpo del instrumento.', 'La fila de cuerdas incluye técnicas distintas: guitarra y arpa suelen pulsarse; violín y violonchelo suelen tocarse con arco. Dividir por esas acciones respondería a una pregunta más específica y rompería el grupo de cuatro.'] },
        { heading: 'Mantén el mismo nivel de detalle', paragraphs: ['Son familias habituales, no un inventario de todos los instrumentos ni de todos los sistemas acústicos. La selección evita casos como el piano, que puede provocar discusiones sobre cuerdas, percusión y teclados.', 'Al evaluar otra solución, comprueba el nivel de descripción. Una fila por familia y otra por técnica mezclan criterios. Lleva esta comprobación al siguiente acertijo: conserva tanto la propiedad como su grado de detalle.'] },
      ],
    },
  },
};
