import { spawnSync } from 'node:child_process';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { assertValidAuthoringPuzzle } from '../src/domain/puzzle/validator.ts';
import type { AuthoringPuzzleRecord } from '../src/domain/puzzle/authoring';

export type SeedExecutionMode = 'local' | 'remote';

export interface SeedCommandOptions {
  readonly contentRoot: string;
  readonly outputPath: string;
  readonly databaseName?: string;
  readonly executionMode?: SeedExecutionMode;
  readonly help: boolean;
}

const projectRoot = fileURLToPath(new URL('..', import.meta.url));
const defaultContentRoot = join(projectRoot, 'content', 'puzzles');

/**
 * Load and validate every JSON authoring record below a content directory.
 * Files are sorted so that generated SQL is reproducible between machines.
 */
export async function loadAuthoringPuzzles(contentRoot: string = defaultContentRoot): Promise<readonly AuthoringPuzzleRecord[]> {
  const resolvedContentRoot = resolve(contentRoot);
  const puzzleFiles = await collectJsonFiles(resolvedContentRoot);
  const records: AuthoringPuzzleRecord[] = [];

  for (const filePath of puzzleFiles) {
    const fileLabel = relative(projectRoot, filePath) || filePath;
    let puzzle: unknown;

    try {
      puzzle = JSON.parse(await readFile(filePath, 'utf8')) as unknown;
    } catch (error) {
      throw new Error(`${fileLabel} is not valid JSON: ${error instanceof Error ? error.message : String(error)}`);
    }

    assertValidAuthoringPuzzle(puzzle, fileLabel);
    records.push(puzzle);
  }

  assertUniqueSeedKeys(records);
  return records;
}

/**
 * Build an idempotent D1 seed script from validated records.
 * The generated SQL intentionally includes complete solution data because it
 * is written to D1, never imported by the browser bundle. Explicit BEGIN and
 * COMMIT statements are omitted because remote `wrangler d1 execute` rejects
 * SQL-managed transactions; D1 executes the statements sequentially.
 */
export function buildSeedSql(
  records: readonly AuthoringPuzzleRecord[],
  generatedAt: string = new Date().toISOString(),
): string {
  if (Number.isNaN(Date.parse(generatedAt))) {
    throw new Error(`generatedAt must be a valid date-time: ${generatedAt}`);
  }

  records.forEach((record, index) => {
    assertValidAuthoringPuzzle(record, `seed record ${index + 1}`);
  });
  assertUniqueSeedKeys(records);

  const statements: string[] = [
    '-- Generated by scripts/seed-puzzles.ts. Do not edit by hand.',
    'PRAGMA foreign_keys = ON;',
  ];

  const orderedRecords = [...records].sort(compareRecords);
  for (const puzzle of orderedRecords) {
    statements.push(...buildPuzzleStatements(puzzle, generatedAt));
  }

  return `${statements.join('\n\n')}\n`;
}

/** Parse the seed CLI without touching the filesystem or invoking Wrangler. */
export function parseSeedArgs(
  argv: readonly string[],
  rootDirectory: string = projectRoot,
): SeedCommandOptions {
  const resolvedRootDirectory = resolve(rootDirectory);
  const contentRoot = join(resolvedRootDirectory, 'content', 'puzzles');
  let outputPath = join(resolvedRootDirectory, '.wrangler', 'tensift-seed.sql');
  let databaseName: string | undefined;
  let executionMode: SeedExecutionMode | undefined;
  let help = false;

  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];

    if (argument === '--help' || argument === '-h') {
      help = true;
      continue;
    }

    if (argument === '--local' || argument === '--remote') {
      const requestedMode = argument.slice(2) as SeedExecutionMode;
      if (executionMode && executionMode !== requestedMode) {
        throw new Error('Choose only one seed execution mode: --local or --remote.');
      }
      executionMode = requestedMode;
      continue;
    }

    if (argument === '--output' || argument === '--database') {
      const value = argv[index + 1];
      if (!value || value.startsWith('--')) {
        throw new Error(`${argument} requires a value.`);
      }
      index += 1;
      if (argument === '--output') {
        outputPath = resolve(rootDirectory, value);
      } else {
        databaseName = value;
      }
      continue;
    }

    if (argument.startsWith('--output=')) {
      const value = argument.slice('--output='.length);
      if (!value) {
        throw new Error('--output requires a value.');
      }
      outputPath = resolve(rootDirectory, value);
      continue;
    }

    if (argument.startsWith('--database=')) {
      const value = argument.slice('--database='.length);
      if (!value) {
        throw new Error('--database requires a value.');
      }
      databaseName = value;
      continue;
    }

    throw new Error(`Unknown seed option: ${argument}`);
  }

  if (help) {
    return {
      contentRoot,
      outputPath,
      databaseName,
      executionMode,
      help: true,
    };
  }

  if (databaseName && !executionMode) {
    throw new Error('--database requires --local or --remote.');
  }

  if (executionMode && !databaseName) {
    throw new Error(`--${executionMode} requires --database <name>.`);
  }

  return {
    contentRoot,
    outputPath,
    databaseName,
    executionMode,
    help: false,
  };
}

/** Run the seed workflow, optionally applying the generated file through Wrangler D1. */
export async function runSeedCommand(options: SeedCommandOptions): Promise<void> {
  if (options.help) {
    console.log(SEED_HELP_TEXT);
    return;
  }

  const records = await loadAuthoringPuzzles(options.contentRoot);
  const sql = buildSeedSql(records);
  await mkdir(dirname(options.outputPath), { recursive: true });
  await writeFile(options.outputPath, sql, 'utf8');
  console.log(`D1 seed SQL written to ${relative(projectRoot, options.outputPath) || options.outputPath} (${records.length} puzzles).`);

  if (!options.executionMode || !options.databaseName) {
    console.log('Dry run only: no D1 database was modified.');
    return;
  }

  applySeedWithWrangler(options.databaseName, options.executionMode, options.outputPath);
}

const SEED_HELP_TEXT = `Usage:
  npm run seed:puzzles -- [--output <path>]
  npm run seed:puzzles -- --database <name> --local
  npm run seed:puzzles -- --database <name> --remote

By default the command validates content/puzzles/**/*.json and writes
.wrangler/tensift-seed.sql. It never changes a database unless --local or
--remote is explicitly provided. Remote execution requires an authenticated
Wrangler session and an explicitly supplied database name.
`;

async function collectJsonFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  entries.sort((left, right) => left.name < right.name ? -1 : left.name > right.name ? 1 : 0);

  const files: string[] = [];
  for (const entry of entries) {
    const entryPath = join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...await collectJsonFiles(entryPath));
    } else if (entry.isFile() && entry.name.endsWith('.json')) {
      files.push(entryPath);
    }
  }

  return files;
}

function buildPuzzleStatements(puzzle: AuthoringPuzzleRecord, generatedAt: string): readonly string[] {
  const statements: string[] = [
    `DELETE FROM action_receipts WHERE puzzle_id = ${sqlString(puzzle.puzzleId)};`,
    `DELETE FROM solution_group_items WHERE puzzle_id = ${sqlString(puzzle.puzzleId)};`,
    `DELETE FROM solution_groups WHERE puzzle_id = ${sqlString(puzzle.puzzleId)};`,
    `DELETE FROM puzzle_rows WHERE puzzle_id = ${sqlString(puzzle.puzzleId)};`,
    `DELETE FROM puzzle_items WHERE puzzle_id = ${sqlString(puzzle.puzzleId)};`,
    `DELETE FROM puzzle_sources WHERE puzzle_id = ${sqlString(puzzle.puzzleId)};`,
    `DELETE FROM puzzles WHERE puzzle_id = ${sqlString(puzzle.puzzleId)};`,
    `INSERT INTO puzzles (
  puzzle_id,
  puzzle_family_id,
  locale,
  publish_date,
  timezone,
  status,
  theme,
  hidden_dimension,
  explanation,
  difficulty_band,
  difficulty_score,
  hint_policy,
  max_hints,
  created_at,
  updated_at
) VALUES (
  ${sqlString(puzzle.puzzleId)},
  ${sqlString(puzzle.puzzleFamilyId)},
  ${sqlString(puzzle.locale)},
  ${sqlString(puzzle.publishDate)},
  ${sqlString(puzzle.timezone)},
  ${sqlString(puzzle.status)},
  ${sqlString(puzzle.theme)},
  ${sqlString(puzzle.solution.hiddenDimension)},
  ${sqlString(puzzle.explanation)},
  ${sqlString(puzzle.difficulty.band)},
  ${sqlNumber(puzzle.difficulty.score)},
  ${sqlString(puzzle.hint.policy)},
  ${sqlNumber(puzzle.hint.maxUses)},
  ${sqlString(generatedAt)},
  ${sqlString(generatedAt)}
);`,
  ];

  puzzle.items.forEach((item, index) => {
    statements.push(`INSERT INTO puzzle_items (
  puzzle_id,
  item_id,
  label,
  visual_json,
  rights_note,
  display_order
) VALUES (
  ${sqlString(puzzle.puzzleId)},
  ${sqlString(item.itemId)},
  ${sqlString(item.label)},
  ${item.visual ? sqlString(JSON.stringify(item.visual)) : 'NULL'},
  ${sqlNullableString(item.rightsNote)},
  ${sqlNumber(index + 1)}
);`);
  });

  puzzle.rows.forEach((row) => {
    statements.push(`INSERT INTO puzzle_rows (puzzle_id, row_id, capacity)
VALUES (${sqlString(puzzle.puzzleId)}, ${sqlString(row.rowId)}, ${sqlNumber(row.capacity)});`);
  });

  puzzle.solution.groups.forEach((group, index) => {
    statements.push(`INSERT INTO solution_groups (puzzle_id, group_id, label, capacity, display_order)
VALUES (${sqlString(puzzle.puzzleId)}, ${sqlString(group.groupId)}, ${sqlString(group.label)}, ${sqlNumber(group.capacity)}, ${sqlNumber(index + 1)});`);

    group.itemIds.forEach((itemId) => {
      statements.push(`INSERT INTO solution_group_items (puzzle_id, group_id, item_id)
VALUES (${sqlString(puzzle.puzzleId)}, ${sqlString(group.groupId)}, ${sqlString(itemId)});`);
    });
  });

  puzzle.sources.forEach((source, index) => {
    statements.push(`INSERT INTO puzzle_sources (puzzle_id, source_id, title, url, retrieved_at)
VALUES (${sqlString(puzzle.puzzleId)}, ${sqlString(`source-${index + 1}`)}, ${sqlString(source.title)}, ${sqlString(source.url)}, ${sqlString(source.retrievedAt)});`);
  });

  return statements;
}

function assertUniqueSeedKeys(records: readonly AuthoringPuzzleRecord[]): void {
  const puzzleIds = new Set<string>();
  const localeDates = new Set<string>();

  for (const record of records) {
    if (puzzleIds.has(record.puzzleId)) {
      throw new Error(`Duplicate puzzleId in seed input: ${record.puzzleId}`);
    }
    puzzleIds.add(record.puzzleId);

    const localeDate = `${record.locale}:${record.publishDate}`;
    if (localeDates.has(localeDate)) {
      throw new Error(`Duplicate locale/publishDate in seed input: ${localeDate}`);
    }
    localeDates.add(localeDate);
  }
}

function compareRecords(left: AuthoringPuzzleRecord, right: AuthoringPuzzleRecord): number {
  return left.puzzleId < right.puzzleId ? -1 : left.puzzleId > right.puzzleId ? 1 : 0;
}

function sqlString(value: string): string {
  if (value.includes('\u0000')) {
    throw new Error('Cannot encode NUL characters in D1 seed SQL.');
  }
  return `'${value.replaceAll("'", "''")}'`;
}

function sqlNullableString(value: string | undefined): string {
  return value === undefined ? 'NULL' : sqlString(value);
}

function sqlNumber(value: number): string {
  if (!Number.isFinite(value)) {
    throw new Error(`Cannot encode non-finite number in D1 seed SQL: ${value}`);
  }
  return String(value);
}

function applySeedWithWrangler(
  databaseName: string,
  executionMode: SeedExecutionMode,
  outputPath: string,
): void {
  const wranglerEntrypoint = resolve(projectRoot, 'node_modules', 'wrangler', 'bin', 'wrangler.js');
  const result = spawnSync(
    process.execPath,
    [wranglerEntrypoint, 'd1', 'execute', databaseName, '--file', outputPath, `--${executionMode}`],
    { cwd: projectRoot, stdio: 'inherit' },
  );

  if (result.error) {
    throw new Error(`Unable to invoke Wrangler: ${result.error.message}`);
  }
  if (result.status !== 0) {
    throw new Error(`Wrangler D1 seed failed with exit status ${result.status ?? 'unknown'}.`);
  }

  console.log(`D1 seed applied to ${databaseName} (${executionMode}).`);
}

const isMainModule = process.argv[1]
  ? fileURLToPath(import.meta.url) === resolve(process.argv[1])
  : false;

if (isMainModule) {
  let options: SeedCommandOptions | undefined;
  try {
    options = parseSeedArgs(process.argv.slice(2));
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    console.error(SEED_HELP_TEXT);
    process.exitCode = 1;
  }

  if (options) {
    runSeedCommand(options).catch((error: unknown) => {
      console.error(error instanceof Error ? error.message : String(error));
      process.exitCode = 1;
    });
  }
}
