import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import countriesPuzzle from '../../content/puzzles/en/countries-continent-2026-09-01-en.json';
import instrumentsPuzzle from '../../content/puzzles/en/instruments-family-2026-09-03-en.json';
import type { AuthoringPuzzleRecord } from '../../src/domain/puzzle/authoring';
import { buildSeedSql, loadAuthoringPuzzles, parseSeedArgs } from '../../scripts/seed-puzzles';

const countryRecord = countriesPuzzle as AuthoringPuzzleRecord;
const instrumentsRecord = instrumentsPuzzle as AuthoringPuzzleRecord;
const generatedAt = '2026-08-29T00:00:00.000Z';

describe('D1 puzzle seed generator', () => {
  it('loads and validates the complete ten-day content batch', async () => {
    const records = await loadAuthoringPuzzles();

    expect(records).toHaveLength(30);
    expect(new Set(records.map((record) => record.puzzleId)).size).toBe(30);
    expect(new Set(records.map((record) => record.puzzleFamilyId)).size).toBe(10);
    expect(new Set(records.map((record) => record.locale))).toEqual(new Set(['en', 'es-419', 'zh-Hans']));
    expect(records.some((record) => record.puzzleFamilyId === 'home-room-001')).toBe(true);
    expect(records.some((record) => record.puzzleFamilyId === 'space-objects-001')).toBe(false);
  });

  it('emits deterministic, idempotent SQL for a puzzle record', () => {
    const sql = buildSeedSql([countryRecord], generatedAt);

    expect(sql.startsWith('-- Generated by scripts/seed-puzzles.ts')).toBe(true);
    expect(sql).not.toContain('BEGIN TRANSACTION;');
    expect(sql).not.toContain('COMMIT;');
    expect(sql).toContain("DELETE FROM action_receipts WHERE puzzle_id = 'countries-continent-2026-09-01-en';");
    expect(sql).toContain("INSERT INTO puzzles (");
    expect(sql).toContain("'countries-continent-2026-09-01-en'");
    expect(sql).toContain("'2026-08-29T00:00:00.000Z'");
    expect(sql.match(/INSERT INTO puzzle_items/g)).toHaveLength(10);
    expect(sql.match(/INSERT INTO solution_group_items/g)).toHaveLength(10);
  });

  it('escapes text values before placing them in SQL literals', () => {
    const puzzleWithQuote: AuthoringPuzzleRecord = {
      ...countryRecord,
      explanation: "It's a country's grouping.",
      items: countryRecord.items.map((item, index) =>
        index === 0 ? { ...item, label: "King's island" } : item,
      ),
    };

    const sql = buildSeedSql([puzzleWithQuote], generatedAt);

    expect(sql).toContain("It''s a country''s grouping.");
    expect(sql).toContain("King''s island");
  });

  it('sorts records by puzzle ID and validates apply mode arguments', () => {
    const sql = buildSeedSql([instrumentsRecord, countryRecord], generatedAt);
    const countryPosition = sql.indexOf('countries-continent-2026-09-01-en');
    const instrumentsPosition = sql.indexOf('instruments-family-2026-09-03-en');

    expect(countryPosition).toBeGreaterThan(-1);
    expect(instrumentsPosition).toBeGreaterThan(countryPosition);

    const rootDirectory = resolve('project-root');
    const options = parseSeedArgs(['--database', 'preview', '--local'], rootDirectory);
    expect(options.executionMode).toBe('local');
    expect(options.databaseName).toBe('preview');
    expect(options.outputPath).toBe(resolve(rootDirectory, '.wrangler', 'tensift-seed.sql'));
    expect(() => parseSeedArgs(['--remote'])).toThrow('--remote requires --database <name>.');
    expect(() => parseSeedArgs(['--local', '--remote'])).toThrow('Choose only one seed execution mode');
  });
});
